name: Build and Deploy Documentation
on:
  push:
    branches:
      - main

# Permissions needed for GitHub Pages deployment
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Show directory structure
        run: |
          echo "Root directory contents:"
          ls -la
          echo "Finding Makefile and conf.py:"
          find . -name "Makefile" -o -name "conf.py"
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          # Add any other dependencies your docs need
          # If you need the citation extension, make sure it's installed
      
      - name: Build documentation directly with sphinx-build
        run: |
          # Find the directory containing conf.py
          CONF_DIR=$(dirname $(find . -name "conf.py" | head -n 1))
          echo "Found conf.py in: $CONF_DIR"
          
          # Create build directory
          mkdir -p _build/html
          
          # Run sphinx-build directly instead of using make
          sphinx-build -b html "$CONF_DIR" _build/html
      
      - name: Debug build output
        run: |
          echo "Build output contents:"
          ls -la _build/html/
          
          echo "Checking for index.html:"
          if [ -f "_build/html/index.html" ]; then
            echo "index.html exists!"
          else
            echo "index.html does not exist!"
          fi

      - name: Create .nojekyll file
        run: |
          touch _build/html/.nojekyll
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          force_orphan: true